version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
    
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /tmp/sensadoCargadores.log
    maxBytes: 104857600 # 100MB
    backupCount: 20
    encoding: utf8
    
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file_handler]

